name: Actualización automática IRS

on:
  schedule:
    - cron: '0 5 * * *' # Todos los días a las 5 AM UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Generar nueva versión del HTML
        run: |
          npm install node-fetch@2
          echo "Actualizando datos IRS..."
          # A futuro podés poner aquí una rutina con Node.js para reescribir index.html

      - name: Hacer commit y push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Actualización automática diaria del IRS" || echo "No hay cambios"
          git push
